version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"

  redis:
    image: redis:7-alpine
    # ports:
    #   - "6379:6379"

  backend:
    container_name: nest
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    # ports:
    #   - "3001:3001"
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  frontend:
    container_name: next
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
