version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: db_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    network_mode: host
    ports:
      - "5432:5432"


  redis:
    container_name: redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    network_mode: host

  backend:
    container_name: nest
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    network_mode: host
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis

  frontend:
    container_name: next
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    network_mode: host

volumes:
  pgdata:

